server:
  port: 8083
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  profiles:
    active: test
  application:
    name: group
  cloud:
    discovery:
      enabled: false
  datasource:
#    schema:
#      - classpath:/member-schema.sql
#      - classpath:/login-log-schema.sql
#    data:
#      - classpath:/member-data.sql
#    initialization-mode: always
    #    mySQL setting
#    url: jdbc:mysql://127.0.0.1:3306/msa_jongjun_group?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/msa_jongjun_group?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root@1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

group:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

logging.level:
  org.hibernate.SQL: debug