server:
  port: 8083
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  application:
    name: group
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true # for eureka
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

group:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

logging.level:
  org.hibernate.SQL: debug

