server:
  port: 8083
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  profiles:
    active: test
  application:
    name: group
  cloud:
    discovery:
      enabled: false
  datasource:
    schema:
      - classpath:/group-table-schema.sql
      - classpath:/group-table-member-schema.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

group:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

logging.level:
  org.hibernate.SQL: debug