spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379

server:
  port: 8765

zuul:
  routes:
    auth:
      path: /**
      serviceId: auth #eureka에 등록된 Id를 말한다.
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true