spring:
  application:
    name: zuul

server:
  port: 8765

zuul:
  routes:
    auth:
      path: /auths/**
      serviceId: auth #eureka에 등록된 Id를 말한다.
      stripPrefix: false

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/