server:
  port: 8086
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  application:
    name: email
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: auth
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
#      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

# admin 구글 계정
AdminMail:
  id: belljun3395@gmail.com
  password: apglaiqjxnlqxste