server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  profiles:
    active: dev
  application:
    name: auth
  cloud:
    discovery:
      enabled: false # for eureka
  datasource:
    schema:
      - classpath:/member-schema.sql
      - classpath:/login-log-schema.sql
    data:
      - classpath:/member-data.sql
    initialization-mode: always
    url: jdbc:log4jdbc:h2:tcp://localhost/~/msa_jongjun;MODE=MYSQL
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

hystrix:
  command:
    authInfo:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50
#    FeignClass#method(Params):
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000   # default 1,000ms
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

auth:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

logging.level:
  org.hibernate.SQL: debug

