server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  profiles:
    active: dev
  application:
    name: auth
  cloud:
    discovery:
      enabled: false # for eureka
  datasource:
    schema:
      - classpath:/member-schema.sql
      - classpath:/login-log-schema.sql
    data:
      - classpath:/member-data.sql
    initialization-mode: always
    url: jdbc:log4jdbc:h2:tcp://localhost/~/msa_jongjun;MODE=MYSQL
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9093 #h2와 포트 동일
    consumer:
      group-id: auth

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

logging.level:
  org.hibernate.SQL: debug
