server:
  port: 8081

spring:
  application:
    name: auth

hystrix:
  command:
    authInfo:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50
#    FeignClass#method(Params):
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000   # default 1,000ms
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

auth:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

feign:
  hystrix:
    enabled: true
