drop table if exists member CASCADE;

create table member
(
    member_id       bigint generated by default as identity,
    member_role     varchar(255),
    member_email    varchar(255),
    member_name     varchar(255),
    member_password varchar(255),
    primary key (member_id)
);

INSERT INTO member(member_role, member_email, member_name, member_password)
values ('MEMBER', 'kjj395@naver.com', '김종준1', '1234');
INSERT INTO member(member_role, member_email, member_name, member_password)
values ('ADMIN', 'bell3395@gmail.com', '김종준2', '1234');
INSERT INTO member(member_role, member_email, member_name, member_password)
values ('ADMIN', 'jong3395@gmail.com', '김종준3', '1234');
